version: "2"
services:
  postgres-server:
    image: ranger-postgres
    hostname: ranger-for-ads.docker.ads.net
    ports:
      - "5432:5432"
  ranger-admin:
    image: ranger-admin
    stdin_open: true
    depends_on:
      - "postgres-server"
    ports:
      - "6080:6080"
